// The protobus built-in custom types.
//
// These are declared at the ROOT of the type namespace (no package) on
// purpose: the TypeScript and Python ports register them as `.bigint` and
// `.timestamp`, so a shared .proto can write `bigint amount = 1;` and every
// port resolves the same name to the same wire format. Do not add a package.
//
// Shared schemas do not need to import this file. protobus tooling (the
// `protobus` CLI and the protoload package) injects the import when a schema
// uses either type without declaring it. Projects running protoc or buf
// directly add `import "protobus/types.proto";` themselves.
//
// `optional` gives the inner value explicit presence so a zero is still
// written, byte-for-byte as the TypeScript reference writes it. It has no
// effect on what any port decodes.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: protobus/types.proto

package pbtypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// An unsigned integer up to 2^256-1 (uint256-compatible), carried as exactly
// 32 bytes, big-endian. Negative values and values that do not fit are
// refused when encoding, and anything wider than 32 bytes when decoding.
type Bigint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bigint) Reset() {
	*x = Bigint{}
	mi := &file_protobus_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bigint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bigint) ProtoMessage() {}

func (x *Bigint) ProtoReflect() protoreflect.Message {
	mi := &file_protobus_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bigint.ProtoReflect.Descriptor instead.
func (*Bigint) Descriptor() ([]byte, []int) {
	return file_protobus_types_proto_rawDescGZIP(), []int{0}
}

func (x *Bigint) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// An instant, carried as signed milliseconds since the Unix epoch. This is
// not google.protobuf.Timestamp: it has millisecond precision and no
// separate nanos field.
type Timestamp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         *int64                 `protobuf:"varint,1,opt,name=value,proto3,oneof" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Timestamp) Reset() {
	*x = Timestamp{}
	mi := &file_protobus_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Timestamp) ProtoMessage() {}

func (x *Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_protobus_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Timestamp.ProtoReflect.Descriptor instead.
func (*Timestamp) Descriptor() ([]byte, []int) {
	return file_protobus_types_proto_rawDescGZIP(), []int{1}
}

func (x *Timestamp) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

var File_protobus_types_proto protoreflect.FileDescriptor

const file_protobus_types_proto_rawDesc = "" +
	"\n" +
	"\x14protobus/types.proto\"-\n" +
	"\x06bigint\x12\x19\n" +
	"\x05value\x18\x01 \x01(\fH\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_value\"0\n" +
	"\ttimestamp\x12\x19\n" +
	"\x05value\x18\x01 \x01(\x03H\x00R\x05value\x88\x01\x01B\b\n" +
	"\x06_valueB-Z+github.com/ArielLaub/protobus-go/v2/pbtypesb\x06proto3"

var (
	file_protobus_types_proto_rawDescOnce sync.Once
	file_protobus_types_proto_rawDescData []byte
)

func file_protobus_types_proto_rawDescGZIP() []byte {
	file_protobus_types_proto_rawDescOnce.Do(func() {
		file_protobus_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobus_types_proto_rawDesc), len(file_protobus_types_proto_rawDesc)))
	})
	return file_protobus_types_proto_rawDescData
}

var file_protobus_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobus_types_proto_goTypes = []any{
	(*Bigint)(nil),    // 0: bigint
	(*Timestamp)(nil), // 1: timestamp
}
var file_protobus_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobus_types_proto_init() }
func file_protobus_types_proto_init() {
	if File_protobus_types_proto != nil {
		return
	}
	file_protobus_types_proto_msgTypes[0].OneofWrappers = []any{}
	file_protobus_types_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobus_types_proto_rawDesc), len(file_protobus_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobus_types_proto_goTypes,
		DependencyIndexes: file_protobus_types_proto_depIdxs,
		MessageInfos:      file_protobus_types_proto_msgTypes,
	}.Build()
	File_protobus_types_proto = out.File
	file_protobus_types_proto_goTypes = nil
	file_protobus_types_proto_depIdxs = nil
}
