// Code generated by protoc-gen-go-protobus. DO NOT EDIT.
// versions:
// - protoc-gen-go-protobus v2.0.0
// source: gentest.proto

package gentest

import (
	pbtypes "github.com/ArielLaub/protobus-go/v2/pbtypes"
)

import (
	"context"
	"iter"

	"google.golang.org/protobuf/proto"

	protobus "github.com/ArielLaub/protobus-go/v2"
)

// This file requires protobus-go v2.
var _ = protobus.Version

// Calc_ServiceName is the fully-qualified name of the GenTest.Calc service.
const Calc_ServiceName = "GenTest.Calc"

// Calc adds and counts.
//
// Implementations should embed UnimplementedCalcServer so that adding a method to the
// service does not break them: an unimplemented method answers its caller
// with a PROTOCOL_ERROR.
type CalcServer interface {
	// add returns a + b.
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Count serves the count method.
	Count(context.Context, *CountRequest, protobus.ServerStream[*CountChunk]) error
	// Takes and returns a type from another Go package.
	Double(context.Context, *pbtypes.Bigint) (*pbtypes.Bigint, error)
	// Unimplemented serves the unimplemented method.
	Unimplemented(context.Context, *AddRequest) (*AddResponse, error)
}

// UnimplementedCalcServer answers every method with protobus.ErrUnimplemented.
type UnimplementedCalcServer struct{}

func (UnimplementedCalcServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, protobus.ErrUnimplemented
}

func (UnimplementedCalcServer) Count(context.Context, *CountRequest, protobus.ServerStream[*CountChunk]) error {
	return protobus.ErrUnimplemented
}

func (UnimplementedCalcServer) Double(context.Context, *pbtypes.Bigint) (*pbtypes.Bigint, error) {
	return nil, protobus.ErrUnimplemented
}

func (UnimplementedCalcServer) Unimplemented(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, protobus.ErrUnimplemented
}

// Calc_ServiceDesc describes the GenTest.Calc service for protobus.Bus.Register.
var Calc_ServiceDesc = protobus.ServiceDesc{
	ServiceName: Calc_ServiceName,
	HandlerType: (*CalcServer)(nil),
	Methods: []protobus.MethodDesc{
		{
			MethodName: "add",
			Handler: func(srv any, ctx context.Context, dec protobus.DecodeFunc) (proto.Message, error) {
				in := new(AddRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				return srv.(CalcServer).Add(ctx, in)
			},
		},
		{
			MethodName: "double",
			Handler: func(srv any, ctx context.Context, dec protobus.DecodeFunc) (proto.Message, error) {
				in := new(pbtypes.Bigint)
				if err := dec(in); err != nil {
					return nil, err
				}
				return srv.(CalcServer).Double(ctx, in)
			},
		},
		{
			MethodName: "unimplemented",
			Handler: func(srv any, ctx context.Context, dec protobus.DecodeFunc) (proto.Message, error) {
				in := new(AddRequest)
				if err := dec(in); err != nil {
					return nil, err
				}
				return srv.(CalcServer).Unimplemented(ctx, in)
			},
		},
	},
	Streams: []protobus.StreamDesc{
		{
			MethodName: "count",
			Handler: func(srv any, ctx context.Context, dec protobus.DecodeFunc, stream protobus.RawServerStream) error {
				in := new(CountRequest)
				if err := dec(in); err != nil {
					return err
				}
				return srv.(CalcServer).Count(ctx, in, protobus.NewServerStream[*CountChunk](stream))
			},
		},
	},
}

// RegisterCalcServer prepares srv to serve GenTest.Calc on bus. Call Start on
// the returned service (or pass it to protobus.Run) to begin serving.
func RegisterCalcServer(bus *protobus.Bus, srv CalcServer, opts ...protobus.ServiceOption) (*protobus.Service, error) {
	return bus.Register(&Calc_ServiceDesc, srv, opts...)
}

// Calc adds and counts.
type CalcClient interface {
	// add returns a + b.
	Add(ctx context.Context, in *AddRequest, opts ...protobus.CallOption) (*AddResponse, error)
	// Count calls the count method.
	Count(ctx context.Context, in *CountRequest, opts ...protobus.StreamOption) iter.Seq2[*CountChunk, error]
	// Takes and returns a type from another Go package.
	Double(ctx context.Context, in *pbtypes.Bigint, opts ...protobus.CallOption) (*pbtypes.Bigint, error)
	// Unimplemented calls the unimplemented method.
	Unimplemented(ctx context.Context, in *AddRequest, opts ...protobus.CallOption) (*AddResponse, error)
}

type calcClient struct {
	c *protobus.Client
}

// NewCalcClient returns a client for GenTest.Calc. Pass protobus.ForInstance
// to address a named instance of the service.
func NewCalcClient(bus *protobus.Bus, opts ...protobus.ClientOption) CalcClient {
	return &calcClient{c: protobus.NewClient(bus, Calc_ServiceName, opts...)}
}

func (c *calcClient) Add(ctx context.Context, in *AddRequest, opts ...protobus.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	if err := c.c.Invoke(ctx, "add", in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Count(ctx context.Context, in *CountRequest, opts ...protobus.StreamOption) iter.Seq2[*CountChunk, error] {
	return protobus.Stream[*CountChunk](ctx, c.c, "count", in, opts...)
}

func (c *calcClient) Double(ctx context.Context, in *pbtypes.Bigint, opts ...protobus.CallOption) (*pbtypes.Bigint, error) {
	out := new(pbtypes.Bigint)
	if err := c.c.Invoke(ctx, "double", in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calcClient) Unimplemented(ctx context.Context, in *AddRequest, opts ...protobus.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	if err := c.c.Invoke(ctx, "unimplemented", in, out, opts...); err != nil {
		return nil, err
	}
	return out, nil
}

// Ticker_ServiceName is the fully-qualified name of the GenTest.Ticker service.
const Ticker_ServiceName = "GenTest.Ticker"

// Streams only, to exercise the import set of a streaming-only service.
//
// Implementations should embed UnimplementedTickerServer so that adding a method to the
// service does not break them: an unimplemented method answers its caller
// with a PROTOCOL_ERROR.
//
// Deprecated: Do not use.
type TickerServer interface {
	// Tick serves the tick method.
	Tick(context.Context, *CountRequest, protobus.ServerStream[*CountChunk]) error
}

// UnimplementedTickerServer answers every method with protobus.ErrUnimplemented.
type UnimplementedTickerServer struct{}

func (UnimplementedTickerServer) Tick(context.Context, *CountRequest, protobus.ServerStream[*CountChunk]) error {
	return protobus.ErrUnimplemented
}

// Ticker_ServiceDesc describes the GenTest.Ticker service for protobus.Bus.Register.
var Ticker_ServiceDesc = protobus.ServiceDesc{
	ServiceName: Ticker_ServiceName,
	HandlerType: (*TickerServer)(nil),
	Methods:     []protobus.MethodDesc{},
	Streams: []protobus.StreamDesc{
		{
			MethodName: "tick",
			Handler: func(srv any, ctx context.Context, dec protobus.DecodeFunc, stream protobus.RawServerStream) error {
				in := new(CountRequest)
				if err := dec(in); err != nil {
					return err
				}
				return srv.(TickerServer).Tick(ctx, in, protobus.NewServerStream[*CountChunk](stream))
			},
		},
	},
}

// RegisterTickerServer prepares srv to serve GenTest.Ticker on bus. Call Start on
// the returned service (or pass it to protobus.Run) to begin serving.
//
// Deprecated: Do not use.
func RegisterTickerServer(bus *protobus.Bus, srv TickerServer, opts ...protobus.ServiceOption) (*protobus.Service, error) {
	return bus.Register(&Ticker_ServiceDesc, srv, opts...)
}

// Streams only, to exercise the import set of a streaming-only service.
//
// Deprecated: Do not use.
type TickerClient interface {
	// Tick calls the tick method.
	Tick(ctx context.Context, in *CountRequest, opts ...protobus.StreamOption) iter.Seq2[*CountChunk, error]
}

type tickerClient struct {
	c *protobus.Client
}

// NewTickerClient returns a client for GenTest.Ticker. Pass protobus.ForInstance
// to address a named instance of the service.
//
// Deprecated: Do not use.
func NewTickerClient(bus *protobus.Bus, opts ...protobus.ClientOption) TickerClient {
	return &tickerClient{c: protobus.NewClient(bus, Ticker_ServiceName, opts...)}
}

func (c *tickerClient) Tick(ctx context.Context, in *CountRequest, opts ...protobus.StreamOption) iter.Seq2[*CountChunk, error] {
	return protobus.Stream[*CountChunk](ctx, c.c, "tick", in, opts...)
}
