// Schema used by protobus-go's own tests. Shaped like a typical shared
// protobus schema: no go_package in the original, custom types used without
// an explicit import (the import below is what protobus tooling injects).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.2
// source: test.proto

package testpb

import (
	pbtypes "github.com/ArielLaub/protobus-go/v2/pbtypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN Status = 0
	Status_STATUS_OPEN    Status = 1
	Status_STATUS_CLOSED  Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN",
		1: "STATUS_OPEN",
		2: "STATUS_CLOSED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN": 0,
		"STATUS_OPEN":    1,
		"STATUS_CLOSED":  2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	A             int32                  `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B             int32                  `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetA() int32 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *AddRequest) GetB() int32 {
	if x != nil {
		return x.B
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sum           int32                  `protobuf:"varint,1,opt,name=sum,proto3" json:"sum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetSum() int32 {
	if x != nil {
		return x.Sum
	}
	return 0
}

type FailRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// "handled", "unhandled", "panic", "transient" (fails until attempts > n)
	Mode          string `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Code          string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	SucceedAfter  int32  `protobuf:"varint,4,opt,name=succeed_after,json=succeedAfter,proto3" json:"succeed_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailRequest) Reset() {
	*x = FailRequest{}
	mi := &file_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailRequest) ProtoMessage() {}

func (x *FailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailRequest.ProtoReflect.Descriptor instead.
func (*FailRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{2}
}

func (x *FailRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FailRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FailRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *FailRequest) GetSucceedAfter() int32 {
	if x != nil {
		return x.SucceedAfter
	}
	return 0
}

type SlowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ms            int32                  `protobuf:"varint,1,opt,name=ms,proto3" json:"ms,omitempty"`
	IgnoreCancel  bool                   `protobuf:"varint,2,opt,name=ignore_cancel,json=ignoreCancel,proto3" json:"ignore_cancel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlowRequest) Reset() {
	*x = SlowRequest{}
	mi := &file_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlowRequest) ProtoMessage() {}

func (x *SlowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlowRequest.ProtoReflect.Descriptor instead.
func (*SlowRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{3}
}

func (x *SlowRequest) GetMs() int32 {
	if x != nil {
		return x.Ms
	}
	return 0
}

func (x *SlowRequest) GetIgnoreCancel() bool {
	if x != nil {
		return x.IgnoreCancel
	}
	return false
}

type CountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	N     int32                  `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	// Fail with a HandledError after this many chunks (0 = never).
	FailAt        int32 `protobuf:"varint,2,opt,name=fail_at,json=failAt,proto3" json:"fail_at,omitempty"`
	DelayMs       int32 `protobuf:"varint,3,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	Unhandled     bool  `protobuf:"varint,4,opt,name=unhandled,proto3" json:"unhandled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountRequest) Reset() {
	*x = CountRequest{}
	mi := &file_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountRequest) ProtoMessage() {}

func (x *CountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountRequest.ProtoReflect.Descriptor instead.
func (*CountRequest) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{4}
}

func (x *CountRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *CountRequest) GetFailAt() int32 {
	if x != nil {
		return x.FailAt
	}
	return 0
}

func (x *CountRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *CountRequest) GetUnhandled() bool {
	if x != nil {
		return x.Unhandled
	}
	return false
}

type CountChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	I             int32                  `protobuf:"varint,1,opt,name=i,proto3" json:"i,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountChunk) Reset() {
	*x = CountChunk{}
	mi := &file_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountChunk) ProtoMessage() {}

func (x *CountChunk) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountChunk.ProtoReflect.Descriptor instead.
func (*CountChunk) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{5}
}

func (x *CountChunk) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

type Order struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Id            string                     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *pbtypes.Bigint            `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	PlacedAt      *pbtypes.Timestamp         `protobuf:"bytes,3,opt,name=placed_at,json=placedAt,proto3" json:"placed_at,omitempty"`
	Big           int64                      `protobuf:"varint,4,opt,name=big,proto3" json:"big,omitempty"`
	Tags          []string                   `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	Counts        map[string]int32           `protobuf:"bytes,6,rep,name=counts,proto3" json:"counts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	Balances      map[string]*pbtypes.Bigint `protobuf:"bytes,7,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Parts         []*pbtypes.Bigint          `protobuf:"bytes,8,rep,name=parts,proto3" json:"parts,omitempty"`
	Status        Status                     `protobuf:"varint,9,opt,name=status,proto3,enum=Test.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{6}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetAmount() *pbtypes.Bigint {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Order) GetPlacedAt() *pbtypes.Timestamp {
	if x != nil {
		return x.PlacedAt
	}
	return nil
}

func (x *Order) GetBig() int64 {
	if x != nil {
		return x.Big
	}
	return 0
}

func (x *Order) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Order) GetCounts() map[string]int32 {
	if x != nil {
		return x.Counts
	}
	return nil
}

func (x *Order) GetBalances() map[string]*pbtypes.Bigint {
	if x != nil {
		return x.Balances
	}
	return nil
}

func (x *Order) GetParts() []*pbtypes.Bigint {
	if x != nil {
		return x.Parts
	}
	return nil
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN
}

type OrderCreated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amount        *pbtypes.Bigint        `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	mi := &file_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{7}
}

func (x *OrderCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCreated) GetAmount() *pbtypes.Bigint {
	if x != nil {
		return x.Amount
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	N             *pbtypes.Bigint        `protobuf:"bytes,2,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_test_proto_rawDescGZIP(), []int{8}
}

func (x *Ping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Ping) GetN() *pbtypes.Bigint {
	if x != nil {
		return x.N
	}
	return nil
}

var File_test_proto protoreflect.FileDescriptor

const file_test_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"test.proto\x12\x04Test\x1a\x14protobus/types.proto\"(\n" +
	"\n" +
	"AddRequest\x12\f\n" +
	"\x01a\x18\x01 \x01(\x05R\x01a\x12\f\n" +
	"\x01b\x18\x02 \x01(\x05R\x01b\"\x1f\n" +
	"\vAddResponse\x12\x10\n" +
	"\x03sum\x18\x01 \x01(\x05R\x03sum\"t\n" +
	"\vFailRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12#\n" +
	"\rsucceed_after\x18\x04 \x01(\x05R\fsucceedAfter\"B\n" +
	"\vSlowRequest\x12\x0e\n" +
	"\x02ms\x18\x01 \x01(\x05R\x02ms\x12#\n" +
	"\rignore_cancel\x18\x02 \x01(\bR\fignoreCancel\"n\n" +
	"\fCountRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\x05R\x01n\x12\x17\n" +
	"\afail_at\x18\x02 \x01(\x05R\x06failAt\x12\x19\n" +
	"\bdelay_ms\x18\x03 \x01(\x05R\adelayMs\x12\x1c\n" +
	"\tunhandled\x18\x04 \x01(\bR\tunhandled\"\x1a\n" +
	"\n" +
	"CountChunk\x12\f\n" +
	"\x01i\x18\x01 \x01(\x05R\x01i\"\xb5\x03\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\v2\a.bigintR\x06amount\x12'\n" +
	"\tplaced_at\x18\x03 \x01(\v2\n" +
	".timestampR\bplacedAt\x12\x10\n" +
	"\x03big\x18\x04 \x01(\x03R\x03big\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12/\n" +
	"\x06counts\x18\x06 \x03(\v2\x17.Test.Order.CountsEntryR\x06counts\x125\n" +
	"\bbalances\x18\a \x03(\v2\x19.Test.Order.BalancesEntryR\bbalances\x12\x1d\n" +
	"\x05parts\x18\b \x03(\v2\a.bigintR\x05parts\x12$\n" +
	"\x06status\x18\t \x01(\x0e2\f.Test.StatusR\x06status\x1a9\n" +
	"\vCountsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\x1aD\n" +
	"\rBalancesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\x05value\x18\x02 \x01(\v2\a.bigintR\x05value:\x028\x01\"?\n" +
	"\fOrderCreated\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\x06amount\x18\x02 \x01(\v2\a.bigintR\x06amount\"-\n" +
	"\x04Ping\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x01n\x18\x02 \x01(\v2\a.bigintR\x01n*@\n" +
	"\x06Status\x12\x12\n" +
	"\x0eSTATUS_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vSTATUS_OPEN\x10\x01\x12\x11\n" +
	"\rSTATUS_CLOSED\x10\x022\x91\x02\n" +
	"\x04Calc\x12*\n" +
	"\x03add\x12\x10.Test.AddRequest\x1a\x11.Test.AddResponse\x12,\n" +
	"\x04fail\x12\x11.Test.FailRequest\x1a\x11.Test.AddResponse\x12,\n" +
	"\x04slow\x12\x11.Test.SlowRequest\x1a\x11.Test.AddResponse\x12/\n" +
	"\x05count\x12\x12.Test.CountRequest\x1a\x10.Test.CountChunk0\x01\x12 \n" +
	"\x04echo\x12\v.Test.Order\x1a\v.Test.Order\x12.\n" +
	"\amissing\x12\x10.Test.AddRequest\x1a\x11.Test.AddResponse23\n" +
	"\x05Other\x12*\n" +
	"\x03add\x12\x10.Test.AddRequest\x1a\x11.Test.AddResponseB5Z3github.com/ArielLaub/protobus-go/v2/internal/testpbb\x06proto3"

var (
	file_test_proto_rawDescOnce sync.Once
	file_test_proto_rawDescData []byte
)

func file_test_proto_rawDescGZIP() []byte {
	file_test_proto_rawDescOnce.Do(func() {
		file_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)))
	})
	return file_test_proto_rawDescData
}

var file_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_test_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_test_proto_goTypes = []any{
	(Status)(0),               // 0: Test.Status
	(*AddRequest)(nil),        // 1: Test.AddRequest
	(*AddResponse)(nil),       // 2: Test.AddResponse
	(*FailRequest)(nil),       // 3: Test.FailRequest
	(*SlowRequest)(nil),       // 4: Test.SlowRequest
	(*CountRequest)(nil),      // 5: Test.CountRequest
	(*CountChunk)(nil),        // 6: Test.CountChunk
	(*Order)(nil),             // 7: Test.Order
	(*OrderCreated)(nil),      // 8: Test.OrderCreated
	(*Ping)(nil),              // 9: Test.Ping
	nil,                       // 10: Test.Order.CountsEntry
	nil,                       // 11: Test.Order.BalancesEntry
	(*pbtypes.Bigint)(nil),    // 12: bigint
	(*pbtypes.Timestamp)(nil), // 13: timestamp
}
var file_test_proto_depIdxs = []int32{
	12, // 0: Test.Order.amount:type_name -> bigint
	13, // 1: Test.Order.placed_at:type_name -> timestamp
	10, // 2: Test.Order.counts:type_name -> Test.Order.CountsEntry
	11, // 3: Test.Order.balances:type_name -> Test.Order.BalancesEntry
	12, // 4: Test.Order.parts:type_name -> bigint
	0,  // 5: Test.Order.status:type_name -> Test.Status
	12, // 6: Test.OrderCreated.amount:type_name -> bigint
	12, // 7: Test.Ping.n:type_name -> bigint
	12, // 8: Test.Order.BalancesEntry.value:type_name -> bigint
	1,  // 9: Test.Calc.add:input_type -> Test.AddRequest
	3,  // 10: Test.Calc.fail:input_type -> Test.FailRequest
	4,  // 11: Test.Calc.slow:input_type -> Test.SlowRequest
	5,  // 12: Test.Calc.count:input_type -> Test.CountRequest
	7,  // 13: Test.Calc.echo:input_type -> Test.Order
	1,  // 14: Test.Calc.missing:input_type -> Test.AddRequest
	1,  // 15: Test.Other.add:input_type -> Test.AddRequest
	2,  // 16: Test.Calc.add:output_type -> Test.AddResponse
	2,  // 17: Test.Calc.fail:output_type -> Test.AddResponse
	2,  // 18: Test.Calc.slow:output_type -> Test.AddResponse
	6,  // 19: Test.Calc.count:output_type -> Test.CountChunk
	7,  // 20: Test.Calc.echo:output_type -> Test.Order
	2,  // 21: Test.Calc.missing:output_type -> Test.AddResponse
	2,  // 22: Test.Other.add:output_type -> Test.AddResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_test_proto_init() }
func file_test_proto_init() {
	if File_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_test_proto_rawDesc), len(file_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_test_proto_goTypes,
		DependencyIndexes: file_test_proto_depIdxs,
		EnumInfos:         file_test_proto_enumTypes,
		MessageInfos:      file_test_proto_msgTypes,
	}.Build()
	File_test_proto = out.File
	file_test_proto_goTypes = nil
	file_test_proto_depIdxs = nil
}
